services:
  - type: web
    name: knomo-innopitch
    runtime: docker
    plan: free
    healthCheckPath: /api/health
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
